"""Initial migration

Revision ID: 2d7ecac53884
Revises: 716224414d3c
Create Date: 2024-08-22 20:44:55.725782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d7ecac53884'
down_revision: Union[str, None] = '716224414d3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parking_lot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('total_spaces', sa.Integer(), nullable=False),
    sa.Column('available_spaces', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parking_lot_id'), 'parking_lot', ['id'], unique=False)
    op.add_column('parking_rates', sa.Column('total_spaces', sa.Integer(), nullable=False))
    op.add_column('parking_rates', sa.Column('available_spaces', sa.Integer(), nullable=False))
    op.drop_column('users', 'car_number')
    op.add_column('vehicles', sa.Column('brand_model', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_vehicles_brand_model'), 'vehicles', ['brand_model'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vehicles_brand_model'), table_name='vehicles')
    op.drop_column('vehicles', 'brand_model')
    op.add_column('users', sa.Column('car_number', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('parking_rates', 'available_spaces')
    op.drop_column('parking_rates', 'total_spaces')
    op.drop_index(op.f('ix_parking_lot_id'), table_name='parking_lot')
    op.drop_table('parking_lot')
    # ### end Alembic commands ###
