"""vehicle mmodel edit2

Revision ID: 0c3d0ef5979c
Revises: c701a29a1935
Create Date: 2024-08-25 12:52:35.535491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c3d0ef5979c'
down_revision: Union[str, None] = 'c701a29a1935'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
