"""parking record edit3

Revision ID: 0f3cbe53096f
Revises: 4dbdfd2e8fb2
Create Date: 2024-08-25 21:22:00.131251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f3cbe53096f'
down_revision: Union[str, None] = '4dbdfd2e8fb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parking_lot', sa.Column('is_occupied', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parking_lot', 'is_occupied')
    # ### end Alembic commands ###
