"""parking record edit5

Revision ID: 220c17193b01
Revises: a1e1c8b773a4
Create Date: 2024-08-26 10:13:33.512560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '220c17193b01'
down_revision: Union[str, None] = 'a1e1c8b773a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_parking_records_license_plate', table_name='parking_records')
    op.create_index(op.f('ix_parking_records_license_plate'), 'parking_records', ['license_plate'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_parking_records_license_plate'), table_name='parking_records')
    op.create_index('ix_parking_records_license_plate', 'parking_records', ['license_plate'], unique=True)
    # ### end Alembic commands ###
