"""parking table edit

Revision ID: 3494511389f1
Revises: e125646cf932
Create Date: 2024-08-24 23:16:18.023930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3494511389f1'
down_revision: Union[str, None] = 'e125646cf932'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parking_records', sa.Column('license_plate', sa.String(length=20), nullable=False))
    op.create_index(op.f('ix_parking_records_license_plate'), 'parking_records', ['license_plate'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_parking_records_license_plate'), table_name='parking_records')
    op.drop_column('parking_records', 'license_plate')
    # ### end Alembic commands ###
