"""parking record edit

Revision ID: 4dbdfd2e8fb2
Revises: 6c2e4b85d3b9
Create Date: 2024-08-25 19:29:06.647747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4dbdfd2e8fb2'
down_revision: Union[str, None] = '6c2e4b85d3b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parking_records', sa.Column('license_plate', sa.String(length=20), nullable=False))
    op.create_index(op.f('ix_parking_records_license_plate'), 'parking_records', ['license_plate'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_parking_records_license_plate'), table_name='parking_records')
    op.drop_column('parking_records', 'license_plate')
    # ### end Alembic commands ###
