"""parking table adding back

Revision ID: 6c2e4b85d3b9
Revises: 92e299daa929
Create Date: 2024-08-25 19:27:30.545791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c2e4b85d3b9'
down_revision: Union[str, None] = '92e299daa929'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parking_lot',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('license_plate', sa.String(length=20), nullable=False),
    sa.Column('entry_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parking_lot_id'), 'parking_lot', ['id'], unique=False)
    op.create_index(op.f('ix_parking_lot_license_plate'), 'parking_lot', ['license_plate'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_parking_lot_license_plate'), table_name='parking_lot')
    op.drop_index(op.f('ix_parking_lot_id'), table_name='parking_lot')
    op.drop_table('parking_lot')
    # ### end Alembic commands ###
