"""vehicle mmodel edit3

Revision ID: 8a5cb0b9ba04
Revises: 0c3d0ef5979c
Create Date: 2024-08-25 13:38:06.558864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a5cb0b9ba04'
down_revision: Union[str, None] = '0c3d0ef5979c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
