"""parking rate added backs

Revision ID: 933557793697
Revises: f8bb8217e067
Create Date: 2024-08-26 20:35:08.217890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '933557793697'
down_revision: Union[str, None] = 'f8bb8217e067'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('parking_rates')


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
