"""parking record edit4

Revision ID: a1e1c8b773a4
Revises: 0f3cbe53096f
Create Date: 2024-08-25 21:26:51.231027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1e1c8b773a4'
down_revision: Union[str, None] = '0f3cbe53096f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
