"""vehicle mmodel back

Revision ID: b77bce51625c
Revises: b2d8a4f96551
Create Date: 2024-08-25 16:35:03.912772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b77bce51625c'
down_revision: Union[str, None] = 'b2d8a4f96551'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vehicles', 'license_plate',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vehicles', 'license_plate',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=False)
    # ### end Alembic commands ###
