"""vehicle mmodel edit

Revision ID: c701a29a1935
Revises: 3494511389f1
Create Date: 2024-08-25 10:45:00.650145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c701a29a1935'
down_revision: Union[str, None] = '3494511389f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('user_email', sa.String(), nullable=False))
    op.drop_constraint('vehicles_user_id_fkey', 'vehicles', type_='foreignkey')
    op.create_foreign_key(None, 'vehicles', 'users', ['user_email'], ['email'])
    op.drop_column('vehicles', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'vehicles', type_='foreignkey')
    op.create_foreign_key('vehicles_user_id_fkey', 'vehicles', 'users', ['user_id'], ['id'])
    op.drop_column('vehicles', 'user_email')
    # ### end Alembic commands ###
