"""parking rates_spaces

Revision ID: f0fa6fd07e90
Revises: 220c17193b01
Create Date: 2024-08-26 19:00:44.259291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0fa6fd07e90'
down_revision: Union[str, None] = '220c17193b01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_black_listcar_id', table_name='black_listcar')
    op.drop_index('ix_black_listcar_license_plate', table_name='black_listcar')
    op.drop_table('black_listcar')
    op.drop_column('parking_rates', 'available_spaces')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parking_rates', sa.Column('available_spaces', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_table('black_listcar',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('license_plate', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='black_listcar_pkey')
    )
    op.create_index('ix_black_listcar_license_plate', 'black_listcar', ['license_plate'], unique=True)
    op.create_index('ix_black_listcar_id', 'black_listcar', ['id'], unique=False)
    # ### end Alembic commands ###
